<?xml version="1.0"?>
<package format="3">
  <name>carla_waypoint_publisher</name>
  <version>0.0.0</version>
  <description>The carla_waypoint_publisher package</description>
  <maintainer email="carla.simulator@gmail.com">CARLA Simulator Team</maintainer>
  <license>MIT</license>

  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>carla_waypoint_types</exec_depend>
  <exec_depend>ros_compatibility</exec_depend>

  <depend>rclpy</depend>
  
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
