<?xml version="1.0"?>
<package format="3">
  <name>rviz_carla_plugin</name>
  <version>0.0.1</version>
  <description>The carla_ros_bridge package</description>
  <maintainer email="carla.simulator@gmail.com">CARLA Simulator Team</maintainer>
  <license>MIT</license>

  <depend>rclcpp</depend>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rviz_common</depend>

  <build_depend>qtbase5-dev</build_depend>
  <depend>carla_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>carla_ros_scenario_runner_types</depend>
  <exec_depend>libqt5-core</exec_depend>
  <exec_depend>libqt5-gui</exec_depend>
  <exec_depend>libqt5-widgets</exec_depend>
  
  <export>
      <build_type>ament_cmake</build_type>
  </export>
</package>
